#!/bin/bash
pushd . > ~/update-playlist.log
cd /home/anon/Interest/Projects/Songs-Index/
python update-index.py

echo "Uploading to GitHub...."
git add . > ~/update-playlist.log
declare d="$(date -Idate)"
declare t="$(date +%T)"
git commit -m "Updated on $d at $t" > ~/update-playlist.log
git push > ~/update-playlist.log
echo "#######################################################"
printf '\n'
echo "All Done!"
echo "View the latest index here:"
printf "\t "
echo "http://bit.do/Songs-Index"
popd >> ~/update-playlist.log
rm ~/update-playlist.log
printf '\n'
echo "#######################################################"
