#!/bin/bash
pushd .
cd /home/anon/Interest/Projects/Songs-Index/
python update-index.py

printf "Uploading to GitHub...."
git add . > ~/update-playlist.log
declare d="$(date -Idate)"
declare t="$(date +%T)"
git commit -m "Updated on $d at $t" >> ~/update-playlist.log
git push >> ~/update-playlist.temp
echo "Done"
popd >> ~/update-playlist.temp
rm ~/update-playlist.log
